FROM python:3.11

WORKDIR /client-app

ENV PYTHONPATH "${PYTHONPATH}:/client-app"

ADD Client/client_socket.py ./Client/
ADD Database/database.py ./Database/
ADD Authentication/auth.py ./Authentication/
ADD Client/strategy.py ./Client/
ADD Client/arena.py ./Client/

CMD [ "python", "./Client/client_socket.py" ]